public interface GedConstants {

   final public int NULL_ID = -1;

   /**
    * Number of state/abbreviation pairs in the STATES array
    */
   final public int STATE_COUNT = 51;

   final public int INDIVIDUAL_COUNT = 851;

   final public String[] STATES = {
      "Alabama", "AL",
      "Alaska", "AK",
      "Arizona", "AZ",
      "Arkansas", "AR",
      "California", "CA",
      "Colorado", "CO",
      "Connecticut", "CT",
      "Delaware", "DE",
      "Florida", "FL",
      "Georgia", "GA",
      "Hawaii", "HI",
      "Idaho", "ID",
      "Illinois", "IL",
      "Indiana", "IN",
      "Iowa", "IA",
      "Kansas", "KS",
      "Kentucky", "KY",
      "Louisiana", "LA",
      "Maine", "ME",
      "Maryland", "MD",
      "Mass.", "MA",
      "Massachusetts", "MA",
      "Michigan", "MI",
      "Minnesota", "MN",
      "Mississippi", "MS",
      "Missouri", "MO",
      "Montana", "MT",
      "Nebraska", "NE",
      "Nevada", "NV",
      "New Hampshire", "NH",
      "New Jersey", "NJ",
      "New Mexico", "NM",
      "New York", "NY",
      "North Carolina", "NC",
      "North Dakota", "ND",
      "Ohio", "OH",
      "Oklahoma", "OK",
      "Oregon", "OR",
      "Pennsylvania", "PA",
      "Rhode Island", "RI",
      "South Carolina", "SC",
      "South Dakota", "SD",
      "Tennessee", "TN",
      "Texas", "TX",
      "Utah", "UT",
      "Vermont", "VT",
      "Virginia", "VA",
      "Washington", "WA",
      "West Virginia", "WV",
      "Wisconsin", "WI",
      "Wyoming", "WY",

      // Non-U.S. states
      "Schleswig-Holstein" // Germany
   };

   final public String[] COUNTRIES = {
      "America",
      "Bahamas",
      "Canada",
      "Denmark",
      "Deutschland",
      "England",
      "France",
      "Germany",
      "Ireland",
      "Israel",
      "Jamaica",
      "Northern Ireland",
      "Norway",
      "Scotland",
      "USA",
      "United States of America",
      "United States"
   };

   final public String[] CITIES = {
      "Abbot",
      "Abington",
      "Acworth",
      "Albany",
      "Alburgh",
      "Alburg",
      "Aldenham",
      "Allenstown",
      "Amesbury",
      "Amherst",
      "Andover",
      "Arundel",
      "Athans",
      "Atkinson",
      "Badlesmere",
      "Bedford",
      "Belfast",
      "Belmont",
      "Berwick On Tweed",
      "Biddeford",
      "Black Point",
      "Blanchard",
      "Bocking",
      "Boston",
      "Boxford",
      "Bradford",
      "Braintree",
      "Brewer",
      "Bridgewater",
      "Brighton",
      "Buckfield",
      "Burlington",
      "Cambridge",
      "Cape Cod Harbor",
      "Cape Elizabeth",
      "Carmel",
      "Carrick",
      "Charleston",
      "Chelmsford",
      "Chesterfield",
      "Chickasaw",
      "Claremont",
      "Crescent City",
      "Cumberland",
      "Deer Isle",
      "Deering",
      "Dorchester",
      "Dover Foxcroft",
      "Dover Town",
      "Dover-Foxcroft",
      "Dover",
      "Durham",
      "East Baldwin",
      "East Bridgewater",
      "East Dover",
      "East Livermore",
      "East Oakland",
      "Easton",
      "Era",
      "Essex",
      "Foxcroft",
      "Francestown",
      "Franklin",
      "Garland",
      "Georgia",
      "Gilmanton",
      "Gorham",
      "Grafton",
      "Gray",
      "Grey",
      "Grittleden",
      "Guilford",
      "Hampton Falls",
      "Hampton",
      "Hanover",
      "Harrington",
      "Haverhill",
      "Index",
      "Ipswich",
      "Kensington",
      "Kingston",
      "Kittery",
      "Lancaster",
      "Lempster",
      "Livermore Falls",
      "Livermore Falls Village",
      "London",
      "Los Angeles",
      "Lowell",
      "Lynn",
      "MA",
      "Madison",
      "Maidstone",
      "Marr",
      "Massachusetts Colony",
      "Merrimack",
      "Miami",
      "Middleborough",
      "Milton",
      "Minneapolis",
      "New England",
      "Newburyport",
      "Newbury",
      "Newport",
      "North Yarmouth",
      "Northampton",
      "Northfield",
      "Nottingham West",
      "Nottingham",
      "Olympia",
      "Opa Locka",
      "Opa-locka",
      "Orlando",
      "Phillips",
      "Plaistow",
      "Plymouth",
      "Portland City",
      "Portland",
      "Providence",
      "Putnam",
      "Ramsey",
      "Raymond",
      "Reading",
      "Rehoboth",
      "Reservation",
      "Rodborne",
      "Romsey",
      "Saco",
      "Salem",
      "Salisbury",
      "Salt Lake City",
      "Sangerville",
      "Scarborough",
      "Scarbough",
      "Searsmont",
      "Seghill",
      "South Hampton",
      "South Portland City",
      "South Portland City (West Part)",
      "South Portland",
      "Southampton",
      "Southold",
      "Spokane",
      "St Albans",
      "St Albens Abbey",
      "Staplehurst",
      "Sumner Town",
      "Taunton",
      "Tiverton",
      "Wenham",
      "West Mill",
      "Westbrook",
      "Westmills",
      "Westmill",
      "Weymouth",
      "Williston",
      "Woburn",
      "Woodbridge",
      "Wotton",
      "Writtle",
      "Yarmouth",
      "York",

      // Denmark
      "Als",
      "Arhus",
      "Brede",
      "Diakonissestiftelsen",
      "Frederiksberg",
      "Hellerup",
      "Kobenhavn",
      "Lyngby",
      "Nakskov",
      "Randers",
      "Ringkobing",
      "Sonderborg",
      "Sønderborg",
      "Tandslet",
      "Tønder",

      // Scotland
      "Aberdeenshire",
      "Annandale",
      "Argyle",      // Apparent misspelling of "Argyll"
      "Argyll",      // Really a registration county in Scotland
      "Aryshire",    // Apparent misspelling of "Ayrshire"
      "Ayrshire",    // Really a registration county in Scotland
      "Ayr",
      "BathgateCastle",
      "Blackhall",
      "Cadder",
      "Cargill",
      "Castle Dumferline",
      "Clareinch",   // Really an island
      "Clydesdale",
      "Colmonell",
      "Cromarty",
      "Cullen",
      "Cunninghame",
      "Dalkeith",
      "Darnley",
      "Dispensation",
      "Douglas",
      "Drumglass",
      "Dumferline",
      "Dumfries",
      "Dundonald",
      "Dunfermline",
      "Edinburg Castle",
      "Edinburgh",
      "Erskine",
      "Falkland",
      "Firth",
      "Girvan",
      "Glasgow",
      "Haddington",
      "Inchmohomo",
      "Inverkip",
      "Irvine",
      "Kilbride",
      "Kilfinan",
      "Kilmarnock",
      "Kyle",
      "Lincluden Church",
      "Lorn",
      "Menteith",
      "Perston",
      "Perth",
      "Restalrig",
      "Rhu",
      "Roseneath",
      "Ross",
      "Scone",
      "Sterling",  // Apparent misspelling of "Stirling"
      "Stobhall",
      "Stralochlan",
      "Stranith Nithsdale",
      "Strathlachlan",
      "Turnberry",
      "ralston",

      // Ireland
      "Connaught",

      // France
      "Avignon",
      "Orléans",
      "Verneuil",
      "Y",

      // Germany
      "Flensborg",   // Danish spelling of "Flensburg"
      "Flensburg",
      "Lã Beck",
      "Meldorf",
      "Sonderburg",
      "Sönderby",

      // Prussia
      "Wezzdowen"
   };

   final public String[] COUNTIES = {
      "Androscoggin",
      "Angusshire",
      "Ardgowan",
      "Argyll",
      "Ayrshire",
      "Baltimore",
      "Banffshire",
      "Barnstable",
      "Belknap",
      "Bristol",
      "Cheshire",
      "Chittenden",
      "Clare",
      "Cooke",
      "Cumberland County",
      "Cumberland",
      "Dade",
      "Del Norte",
      "Devon",
      "Dithmarschen",
      "Dumfries-shire",
      "Dunbartonshire",
      "Durham",
      "East Lothian",
      "Essex",
      "Fifeshiire",
      "Fifeshire",
      "Fife",
      "Franklin",
      "Gentofte",
      "Gloucestershire",
      "Grafton",
      "Grand Isle",
      "Hampshire",
      "Hancock",
      "Harts",
      "Hennepin",
      "Hertfordshire",
      "Hertsford",
      "Hettinger",
      "Hillsborough",
      "Kent",
      "Kincardineshire",
      "Kobenhavn",
      "Lanarkshire",
      "Lancashire",
      "London",
      "Los Angeles",
      "Madison",
      "Mercer",
      "Middlesex County",
      "Middlesex",
      "Midlothian",
      "Newport",
      "Norfolk",
      "Northumberland",
      "Orkney",
      "Oxford",
      "Penobscot",
      "Perthshire",
      "Piscataquis",
      "Plymouth Co",
      "Plymouth",
      "Providence",
      "Refrewshire",
      "Rendsburg-Eckernforde",
      "Renfrewshire",
      "Rockingham",
      "Ross & Cromarty",
      "Ross &amp; Cromarty",
      "Salt Lake",
      "Seward",
      "Snohomish",
      "Somerset",
      "Sonderjylland",
      "Spokane",
      "Storstrom",
      "Suffolk Co",
      "Suffolk",
      "Sullivan",
      "Sussex County",
      "Thurston",
      "Waldo",
      "Washington",
      "Wilkshire",
      "Wiltshire",
      "Windham",
      "Yellowstone",
      "Yorkshire",
      "York",
      "Young"
   };


   final public String[] DANISH_REGIONS = {
      "Nordjylland"
   };

   final public String[] FRENCH_DEPARTMENTS = {
      "Allier",
      "Jura",
      "Loiret",
      "Somme"
   };

   final public String[] PROVINCES = {
      "Franche-Comte",
      "Ostpreussen",
      "Quebec"
   };


   final public String
         INDIVIDUAL = "INDI",
         BIRTH = "BIRT",
         DATE = "DATE",
         PLACE = "PLAC",
         SOURCE = "SOUR",
         NOTE = "NOTE",
         TEXT = "TEXT",
         RESIDENCE = "RESI",
         SEX = "SEX",
         EDUCATION = "EDUC",
         COUNTRY = "NATI",
         RELIGION = "RELI",
         DESCRIPTION = "DSCR",
         UID = "UID",
         APID = "_APID",
         FAMC = "FAMC",       // Family in which individual is a child
         FAMS = "FAMS",       // Family in which individual is a spouse/parent
         DEATH = "DEAT",
         BURIAL = "BURI",
         MARRIED = "MARR",
         DATA = "DATA",
         PAGE = "PAGE",
         EVENT = "EVEN",
         TYPE = "TYPE",
         BAPM = "BAPM",       // Baptism (1 occurrence)
         FAMILY = "FAM",
         HUSBAND = "HUSB",
         WIFE = "WIFE",
         CHILD = "CHIL",
         MREL = "_MREL",      // Not sure what MREL and FREL do; in all cases the value is "Natural"
         FREL = "_FREL",      // Occurs in GED/FAM/CHIL
         DIV = "DIV",         // Not sure about this one either; appears in GED/FAM; content is "Y"
         ANNULLMENT = "ANUL",
         REPO = "REPO",       // Repository?
         ADDRESS = "ADDR",    // Refers to a web address
         AUTHOR = "AUTH",
         PUBLICATION = "PUBL",
         CONCLUSION = "CONC", // Seems to contain the remainder of a truncated string
         TRLR = "TRLR",       // Empty element at end of doc

         NAME = "NAME",
         SURNAME = "SURN",

         OCCUPATION = "OCCU",

         OBJECT = "OBJE",
         TITLE = "TITL",
         FILE = "FILE",

         GED = "GED",
         HEAD = "HEAD",
         CHARSET = "CHAR",
         VERSION = "VERS",
         CORPORATION = "CORP",
         GEDC = "GEDC",
         FORM = "FORM";
}